import React from "react";

export const hairImages = {
    blockOne: [
        {
            url:'./images/IMG_0024.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0125.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0158.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0438.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0555.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0677.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0718.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1051.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1085.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1181.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1221.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1326.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1419.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1441.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1442.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1545.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1611.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1638.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1691.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1825.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1919.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1976.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_2285.jpg',
            size:'vertical'
        },
    ],
    blockTwo: [
        {
            url:'./images/IMG_2641.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_2810.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_3280.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_3454.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_3581.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_3649.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_3789.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_3947.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4056.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4124.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4224.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4304.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4351.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4474.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4510.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4563.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4620.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4649.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4680.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4743.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4771.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_6037.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_6663.jpg',
            size:'vertical'
        },
        
    ],
    blockThree: [
        {
            url:'./images/IMG_6796.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_7287.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_7442.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_7740.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_7828.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_7861.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_8019.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_8023.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_8224.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_8360.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_8424.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_8580.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_8713.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_8787.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_8909.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_9010.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_9028.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_9057.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_9374.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_9466.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_9952.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_372701.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_379101.jpg',
            size:'vertical'
        },
    ]
}