import React from "react";

export const creativeImages = {
    blockOne: [
        {
            url:'./images/IMG_0466.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0515.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0551.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0603.jpg',
            size:'vertical'
        },
        {
            url:'./images/mafa_195.jpg',
            size:'vertical'
        },
        {
            url:'./images/mafa_177.jpg',
            size:'vertical'
        },
        {
            url:'./images/mafa_166.jpg',
            size:'vertical'
        },
    ],
    blockTwo: [
        {
            url:'./images/IMG_1307.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1418.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1455.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1525.jpg',
            size:'horizontal'
        },
        {
            url:'./images/IMG_1589.jpg',
            size:'vertical'
        },
        {
            url:'./images/2W9A0994.jpg',
            size:'vertical'
        },
        {
            url:'./images/2W9A1304.jpg',
            size:'vertical'
        },
        {
            url:'./images/2W9A1333.jpg',
            size:'vertical'
        },
    ],
    blockThree: [
        {
            url:'./images/IMG_0203.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_0212.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1838.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1876.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1908.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_1941.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_2920.jpg',
            size:'vertical'
        },
    ]
}