import React from "react";

export const portalWeddingImages = [
    [
        {
            url:'./images/2W9A6509A.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/2W9A6172.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A6388.avif',
            size:'horizontal'
        },
        {
            url:'./images/2W9A6570A.avif',
            size:'horizontal'
        },
        {
            url:'./images/2W9A7538.avif',
            size:'vertical'
        },
    ],
    [
        {
            url:'./images/2W9A6598.avif',
            size:'horizontal'
        },
        {
            url:'./images/2W9A6692.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/2W9A6751.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/2W9A6873.avif',
            size:'horizontal'
        },
        {
            url:'./images/2W9A8053.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/2W9A7579.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A7685.avif',
            size:'vertical'
        },
        {
            url:'./images/nkwo2W9A0828.avif',
            size:'vertical'
        },
    ],
    [
        {
            url:'./images/2W9A8578A.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A0848.avif',
            size:'vertical'
        },
        {
            url:'./images/nkwo2W9A1218A.avif',
            size:'horizontal'
        },
        {
            url:'./images/nkwo2W9A2290.avif',
            size:'horizontal'
        },
        {
            url:'./images/nkwo2W9A0883.avif',
            size:'vertical'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A3083.avif',
            size:'horizontal'
        },
        {
            url:'./images/nkwo2W9A3103.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A3540.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A3869.avif',
            size:'horizontal'
        },
        {
            url:'./images/nkwoIMG_9998.avif',
            size:'horizontal'
        },
    ],
]

export const mobileWeddingImages = [
    [
        {
            url:'./images/2W9A6509A.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/2W9A6172.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A7538.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A7579.avif',
            size:'vertical'
        },
    ],
    [
        {
            url:'./images/2W9A6388.avif',
            size:'horizontal'
        },
        {
            url:'./images/2W9A6570A.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/2W9A6751.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A0828.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A7685.avif',
            size:'vertical'
        },
        {
            url:'./images/nkwo2W9A0848.avif',
            size:'vertical'
        },
    ],
    [
        {
            url:'./images/2W9A6598.avif',
            size:'horizontal'
        },
        {
            url:'./images/2W9A6692.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/2W9A8578A.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A1218A.avif',
            size:'horizontal'
        },
        {
            url:'./images/nkwo2W9A2290.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A3083.avif',
            size:'horizontal'
        },
        {
            url:'./images/nkwo2W9A3103.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A3540.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A3869.avif',
            size:'horizontal'
        },
        {
            url:'./images/nkwoIMG_9998.avif',
            size:'horizontal'
        },
    ],
    [
        {
            url:'./images/nkwo2W9A0883.avif',
            size:'vertical'
        },
        {
            url:'./images/nkwoIMG_0202.avif',
            size:'vertical'
        },
    ]
]