import React from "react";

export const cosmeticsImages = {
    blockOne: [
        {
            url:'./images/2-06.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A0757.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A0896.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A1216.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_7305.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_9811.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A9929.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A9947.avif',
            size:'vertical'
        },
        {
            url:'./images/NKWO1288.avif',
            size:'vertical'
        },
        {
            url:'./images/NKWO1307.jpg.tmp.avif',
            size:'horizontal'
        },
        {
            url:'./images/NKWO1338.avif',
            size:'vertical'
        },
        {
            url:'./images/NKWO1363.avif',
            size:'horizontal'
        },
        {
            url:'./images/NKWO1904.avif',
            size:'vertical'
        },
        {
            url:'./images/NKWO1934.avif',
            size:'horizontal'
        },
    ],
    blockTwo: [
        {
            url:'./images/2-26.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A0804.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A0948.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A1229.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_0141.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_3673.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_3794-2.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_4300-3.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_5393.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_7153.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_9167.avif',
            size:'vertical'
        },
        {
            url:'./images/NKWO2041.avif',
            size:'horizontal'
        },
    ],
    blockThree: [
        {
            url:'./images/2-50.avif',
            size:'vertical'
        },
        {
            url:'./images/2W9A0837.avif',
            size:'horizontal'
        },
        {
            url:'./images/2W9A1248.avif',
            size:'horizontal'
        },
        {
            url:'./images/2W9A1174.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_7216-2.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_2515.avif',
            size:'vertical'
        },
        {
            url:'./images/IMG_2475.avif',
            size:'horizontal'
        },
        {
            url:'./images/NKWO1967.avif',
            size:'vertical'
        },
        {
            url:'./images/NKWO1984.avif',
            size:'vertical'
        },
        {
            url:'./images/NKWO1998.avif',
            size:'vertical'
        },
        {
            url:'./images/NKWO2080.avif',
            size:'vertical'
        },
        {
            url:'./images/NKWO2083.avif',
            size:'horizontal'
        },
        {
            url:'./images/NKWO2090.avif',
            size:'horizontal'
        },
        {
            url:'./images/NKWO2152.avif',
            size:'vertical'
        },
    ]
}