import React from "react";

export const cosmeticsImages = {
    blockOne: [
        {
            url:'./images/2W9A9929.jpg',
            size:'vertical'
        },
        {
            url:'./images/2W9A9947.jpg',
            size:'vertical'
        },
        {
            url:'./images/NKWO1288.jpg',
            size:'vertical'
        },
        {
            url:'./images/NKWO1307.jpg.tmp.jpeg',
            size:'horizontal'
        },
        {
            url:'./images/NKWO1338.jpg',
            size:'vertical'
        },
        {
            url:'./images/NKWO1363.jpg',
            size:'horizontal'
        },
        {
            url:'./images/NKWO1904.jpg',
            size:'vertical'
        },
        {
            url:'./images/NKWO1934.jpg',
            size:'horizontal'
        },
        {
            url:'./images/NKWO2041.jpg',
            size:'horizontal'
        },
    ],
    blockTwo: [
        {
            url:'./images/IMG_0141.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_3673.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_3794-2.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_4300-3.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_5393.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_7153.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_9167.jpg',
            size:'vertical'
        },
    ],
    blockThree: [
        {
            url:'./images/IMG_2515.jpg',
            size:'vertical'
        },
        {
            url:'./images/IMG_2475.jpg',
            size:'horizontal'
        },
        {
            url:'./images/NKWO1967.jpg',
            size:'vertical'
        },
        {
            url:'./images/NKWO1984.jpg',
            size:'vertical'
        },
        {
            url:'./images/NKWO1998.jpg',
            size:'vertical'
        },
        {
            url:'./images/NKWO2080.jpg',
            size:'vertical'
        },
        {
            url:'./images/NKWO2083.jpg',
            size:'horizontal'
        },
        {
            url:'./images/NKWO2090.jpg',
            size:'horizontal'
        },
        {
            url:'./images/NKWO2152.jpg',
            size:'vertical'
        },
    ]
}